apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: start-nais-io
   namespace: aura
   labels:
      team: aura
spec:
   port: 8080
   ingresses:
     {{#each ingresses as |url|}}
        - {{url}}
     {{/each}}
   image: {{ image }}
   replicas:
      min: 1
      max: 3
      cpuThresholdPercentage: 75
   resources:
      limits:
         cpu: 500m
         memory: 2048Mi
      requests:
         cpu: 100m
         memory: 200Mi
   liveness:
      path: /internal/isalive
      initialDelay: 20
      timeout: 1
      periodSeconds: 5
      failureThreshold: 3
   readiness:
      path: /internal/isready
      initialDelay: 20
      timeout: 1
   prometheus:
      enabled: true
      path: /internal/metrics



