name: Build and deploy main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  BASEIMAGE: "gcr.io/distroless/java17-debian11:nonroot"

jobs:
  build:
    name: Build all the things
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      tag: "${{ steps.build-push-sign.outputs.tag }}"
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@e83639073897b68de235d81a783b2221cc13def7 # ratchet:GitHubSecurityLab/actions-permissions/monitor@v1
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # ratchet:actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # ratchet:gradle/wrapper-validation-action@v1
      - name: Build and test the app
        run: ./gradlew test shadowJar
      -  name: Install cosign
         uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # ratchet:sigstore/cosign-installer@main
         with:
            cosign-release: 'v2.0.0'
      -  name: Verify distroless base image
         run: cosign verify --certificate-identity "keyless@distroless.iam.gserviceaccount.com" --certificate-oidc-issuer "https://accounts.google.com" $BASEIMAGE
      - name: Create SBOM
        run: ./gradlew cyclonedxBom
      -  name: "Build and push image"
         uses: nais/platform-build-push-sign@main # ratchet:exclude
         id: build-push-sign
         with:
            name: start.nais.io
            google_service_account: gh-start-nais.io
            workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
            sbom: build/reports/bom.json
            multi-platform: true

  deploy_to_prod:
    name: Deploy to prod-gcp
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/deploy/actions/deploy@fdd2da585ae15831342aad18847dbcc4213f72fb # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml,.nais/alerts.yaml
          VARS: .nais/prod.yaml
          IMAGE: ${{ env.IMAGE_BASENAME }}:${{ needs.build.outputs.tag }}
